export const Theme = {
  colors: {
    primary: '#0057bd',
    onPrimary: '#f0f2ff',
    primaryContainer: '#6e9fff',
    secondary: '#006668',
    onSecondary: '#bffeff',
    surface: '#f3f7fb',
    onSurface: '#2a2f32',
    surfaceVariant: '#d7dee3',
    onSurfaceVariant: '#575c60',
    surfaceContainer: '#e3e9ee',
    surfaceContainerHigh: '#dde3e8',
    surfaceContainerHighest: '#d7dee3',
    background: '#f3f7fb',
    onBackground: '#2a2f32',
    error: '#b31b25',
    onError: '#ffefee',
    outline: '#73777b',
    outlineVariant: '#a9aeb1',
  },
  darkColors: {
    primary: '#4d8eff',
    onPrimary: '#002a62',
    primaryContainer: '#004ca6',
    secondary: '#00ecef',
    onSecondary: '#003334',
    surface: '#0a0f12',
    onSurface: '#f3f7fb',
    surfaceVariant: '#2a2f32',
    onSurfaceVariant: '#a9aeb1',
    surfaceContainer: '#1a1f23',
    surfaceContainerHigh: '#22272b',
    surfaceContainerHighest: '#2a2f32',
    background: '#0a0f12',
    onBackground: '#f3f7fb',
    error: '#ffb4ab',
    onError: '#690005',
    outline: '#73777b',
    outlineVariant: '#45494d',
  },
  typography: {
    headline: { fontFamily: 'PlusJakartaSans-Bold', fontWeight: '700' as const },
    body: { fontFamily: 'Inter-Regular', fontWeight: '400' as const },
    label: { fontFamily: 'Inter-Medium', fontWeight: '500' as const },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radii: {
    sm: 8,
    md: 16,
    lg: 24,
    full: 9999,
  }
};
