/**
 * API Configuration for Aqualyn.
 * Switch between LOCAL and PRODUCTION IPs here.
 */
export const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";

// Endpoints mapping for easier maintenance
export const ENDPOINTS = {
    AUTH_SYNC: `${API_BASE_URL}/api/auth/sync`,
    AUTH_SYNC_TOKEN: `${API_BASE_URL}/api/auth/sync-token`,
    AUTH_SEND_OTP: `${API_BASE_URL}/api/auth/send-otp`,
    AUTH_VERIFY_OTP: `${API_BASE_URL}/api/auth/verify-otp`,
    USER_PROFILE: (id: string) => `${API_BASE_URL}/api/user/profile/${id}`,
    NOTIFICATIONS: `${API_BASE_URL}/api/user/notifications`,
    FOLLOW: `${API_BASE_URL}/api/user/follow`,
    UNFOLLOW: `${API_BASE_URL}/api/user/unfollow`,
    BLOCK_USER: `${API_BASE_URL}/api/user/block`,
    REPORT_USER: `${API_BASE_URL}/api/user/report`,
    BLOCKED_USERS: `${API_BASE_URL}/api/user/blocked`,
    SETTINGS: `${API_BASE_URL}/api/user/settings`,
    SESSIONS: `${API_BASE_URL}/api/user/sessions`,
    STORAGE_USAGE: `${API_BASE_URL}/api/user/storage-usage`,
    EXPORT_DATA: `${API_BASE_URL}/api/user/export`,
    CONTACT_SYNC: `${API_BASE_URL}/api/user/contacts/sync`,
    CALL_HISTORY: `${API_BASE_URL}/api/user/call-history`,
    UPDATE_SETTINGS: `${API_BASE_URL}/api/user/settings`,
    UPLOAD_AVATAR: `${API_BASE_URL}/api/user/upload-avatar`,
    CHATS: `${API_BASE_URL}/api/chats`,
    CHAT_MESSAGES: (id: string) => `${API_BASE_URL}/api/chats/${id}/messages`,
    MUTE_CHAT: (id: string) => `${API_BASE_URL}/api/chats/${id}/mute`,
    CHAT_MEDIA: (id: string) => `${API_BASE_URL}/api/chats/${id}/media`,
    CHAT_SETTINGS: (id: string) => `${API_BASE_URL}/api/chats/${id}/settings`,
    GROUP_INFO: (id: string) => `${API_BASE_URL}/api/groups/${id}/info`,
    GROUP_LEAVE: (id: string) => `${API_BASE_URL}/api/groups/${id}/leave`,
    GROUP_SETTINGS: (id: string) => `${API_BASE_URL}/api/groups/${id}/settings`,
    USER_SEARCH: (q: string) => `${API_BASE_URL}/api/users/search?q=${encodeURIComponent(q)}`,
    FEED: `${API_BASE_URL}/api/social/feed`,
    STORIES: `${API_BASE_URL}/api/social/stories`,
    CREATE_POST: `${API_BASE_URL}/api/social/post`,
    DELETE_POST: (id: string) => `${API_BASE_URL}/api/social/post/${id}`,
    CREATE_STORY: `${API_BASE_URL}/api/social/story`,
    DELETE_STORY: (id: string) => `${API_BASE_URL}/api/social/story/${id}`,
    LIKE_POST: (id: string) => `${API_BASE_URL}/api/social/post/${id}/like`,
    COMMENT_POST: (id: string) => `${API_BASE_URL}/api/social/post/${id}/comment`,
    GET_FOLLOWERS: (userId: string) => `${API_BASE_URL}/api/user/${userId}/followers`,
    GET_FOLLOWING: (userId: string) => `${API_BASE_URL}/api/user/${userId}/following`,
    USER_POSTS: (userId: string) => `${API_BASE_URL}/api/social/user/${userId}/posts`,
    USER_STORIES: (userId: string) => `${API_BASE_URL}/api/social/user/${userId}/stories`,
    QR_GENERATE: `${API_BASE_URL}/api/auth/qr/generate`,
    QR_STATUS: (token: string) => `${API_BASE_URL}/api/auth/qr/status/${token}`,
    QR_LINK: `${API_BASE_URL}/api/auth/qr/link`,
};
